name: Cypress tests
on:
  workflow-dispatch:
jobs:
  browser:
    continue-on-error: true
    strategy:
      matrix:
        browser: ${{ fromJSON(github.event.inputs.browsers) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Cypress and run tests
        run: npm install
      - name: Log matrix runs
        run: echo ${{matrix.browser}} - ${{github.event.inputs.markets}}
      - name: Cypress run
        id: cypress
        uses: cypress-io/github-action@v6
        with:
          browser: ${{matrix.browser}}
          env: market=${{github.event.inputs.markets}},grepTags=${{github.event.inputs.tags}}
      - name: Get results
        run: |
          echo ${{steps.cypress.conclusion}}
          echo ${{steps.cypress.outcome}}
          echo ${{steps.cypress.outputs.testResults}}
  information:
    runs-on: ubuntu-latest
    steps:
      - name: Run custom action
        uses: ./.github/actions/deploy-s3-javascript
