name: Cypress parallel tests
on:
  workflow_dispatch:
    inputs:
      browsers:
        description: List of browsers for the tests to use
        required: true
        default: '["chrome","firefox","edge"]'
        type: string
      markets:
        description: Markets where the tests should run on
        required: true
        default: '["HU","DE"]'
        type: string
      tags:
        description: Tags should work in this way
        required: true
        default: '@smoke'
        type: string

jobs:
  browser:
    continue-on-error: true
    strategy:
      matrix:
        browser: ${{ fromJSON(github.event.inputs.browsers) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: deps-node-modules-${{hashFiles('**/package-lock.json')}}
      - name: Install Cypress and run tests
        run: npm install
      - name: Log matrix runs
        run: echo ${{matrix.browser}} - ${{github.event.inputs.markets}}
      - name: Cypress run
        id: cypress
        uses: cypress-io/github-action@v6
        with:
          browser: ${{matrix.browser}}
          env: market=${{github.event.inputs.markets}},grepTags=${{github.event.inputs.tags}}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Test Report - ${{matrix.browser}}
          path: cypress/reports

  notify:
    needs: [ browser ]
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Check
        run: echo "hello"

