name: Output information
on:
    workflow_dispatch:
      inputs:
        browser:
          description: List of browsers for the tests to use
          required: false
          default: chrome
          type: string
jobs:
  info:
    continue-on-error: true
    strategy:
      matrix:
        browser: ${{inputs.browser}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Cypress and run tests
        run: npm install
      - name: Start cypress
        id: cypress
        run: npx cypress run --browser ${{matrix.browser}}
      - name: Get results
        run: |
          echo ${{steps.cypress.conclusion}}
          echo ${{steps.cypress.outcome}}
          echo ${{steps.cypress.outputs.testResults}}

