name: Cypress tests
on:
    [ push, workflow_dispatch ]:
      inputs:
        browsers:
          description: List of browsers for the tests to use
          required: true
          default: '["chrome"]'
          type: string
        markets:
          description: Markets where the tests should run on
          required: true
          default: '[["HU","DE"]]'
          type: string
jobs:
  info:
    continue-on-error: true
    strategy:
      matrix:
        browser: ${{ fromJSON(github.event.inputs.browsers) }}
        market: ${{ fromJSON(github.event.inputs.markets) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Cypress and run tests
        run: npm install
      - name: Cypress run
        id: cypress
        run: npx cypress run --browser ${{matrix.browser}} --env market=${{matrix.market}}
      - name: Get results
        run: |
          echo ${{steps.cypress.conclusion}}
          echo ${{steps.cypress.outcome}}
          echo ${{steps.cypress.outputs.testResults}}

