name: Output information
on: workflow_dispatch
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Cypress and run tests
        run: npm install
      - name: Start cypress
        id: cypress
        run: npx cypress open
      - name: Get results
        run: |
          echo ${{steps.cypress.conclusion}}
          echo ${{steps.cypress.outcome}}
          echo ${{steps.cypress.outputs.testResults}}

