name: Output information
on: workflow_dispatch
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Cypress and run tests
        id: cypress
        uses: cypress-io/github-action@v6
      - name: Echo test results
        run: |
          echo ${{steps.cypress.conclusion}}
          echo ${{steps.cypress.outcome}}
          echo ${{steps.cypress.outputs.testResults}}
          echo ${{github}}
