name: Output information
on: workflow_dispatch
jobs:
  info:
    continue-on-error: true
    strategy:
      matrix:
        browser: [chrome, firefox, edge]
        operating-system: [ubuntu-latest, windows-latest]
    runs-on: ${{matrix.operating-system}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Cypress and run tests
        run: npm install
      - name: Start cypress
        id: cypress
        run: npx cypress run --browser ${{browser}}
      - name: Get results
        run: |
          echo ${{steps.cypress.conclusion}}
          echo ${{steps.cypress.outcome}}
          echo ${{steps.cypress.outputs.testResults}}

